/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt 
to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit 
this template
 */
package finalproyect.dataestructure;

import COLAS.*;
import LISTAS_CIRCULARES.*;
import PILAS.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Arman
 */
public class GameInterface extends javax.swing.JFrame {

    public GameInterface() {
        initComponents();
        this.setLocationRelativeTo(null);
        TimerLbl.setText("05:00");

        //inserta los 5 ingredientes
        lis.inserta(new Ingredientes(1, ing.IngredienteAleatorio()));
        lis.inserta(new Ingredientes(2, ing.IngredienteAleatorio()));
        lis.inserta(new Ingredientes(3, ing.IngredienteAleatorio()));
        lis.inserta(new Ingredientes(4, ing.IngredienteAleatorio()));
        lis.inserta(new Ingredientes(5, ing.IngredienteAleatorio()));

        //asigna los labels de ingredientes
        actualizaringredientes();
        downTimer();
        timer.start();
    }

    //variables
    String[][] tiposIngredientes;
    String[] ingPreparacion;
    Timer timer;
    int second = 0;
    int minute = 5;
    String ddSecond, ddMinute;
    DecimalFormat dFormat = new DecimalFormat("00");

    Lista lis = new Lista();
    Ingredientes ing = new Ingredientes();
    Pila pilaPreparar = new Pila();

    Ingredientes ingAux = new Ingredientes();

    //funciones
    public void downTimer() {

        timer = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                second--;
                ddSecond = dFormat.format(second);
                ddMinute = dFormat.format(minute);
                TimerLbl.setText(ddMinute + ":" + ddSecond);

                if (second == -1) {
                    second = 59;
                    minute--;
                    ddSecond = dFormat.format(second);
                    ddMinute = dFormat.format(minute);
                    TimerLbl.setText(ddMinute + ":" + ddSecond);
                }//if
                if (minute == 0 && second == 0) {
                    timer.stop();

                    System.exit(0);
                }
            }

        });

    }//downTimer

    public void actualizaringredientes() {
        tiposIngredientes = lis.obtenerTiposIngredientes();

        ingrediente1Label.setText(tiposIngredientes[0][1]);
        ingrediente2Label.setText(tiposIngredientes[1][1]);
        ingrediente3Label.setText(tiposIngredientes[2][1]);
        ingrediente4Label.setText(tiposIngredientes[3][1]);
        ingrediente5Label.setText(tiposIngredientes[4][1]);
    }//actualizar ingredientes

    public void actualizarpreparacion() {
        pilaPreparar.listar(); //Para pruebas
        ingPreparacion = pilaPreparar.obtenerIngredientespreparacion();
        switch (ingPreparacion.length) {
            case 1:
                labelpreparar1.setText(ingPreparacion[0]);
                break;
            case 2:
                labelpreparar1.setText(ingPreparacion[0]);
                labelpreparar2.setText(ingPreparacion[1]);
                break;
            case 3:
                labelpreparar1.setText(ingPreparacion[0]);
                labelpreparar2.setText(ingPreparacion[1]);
                labelpreparar3.setText(ingPreparacion[2]);
                break;
            case 4:
                labelpreparar1.setText(ingPreparacion[0]);
                labelpreparar2.setText(ingPreparacion[1]);
                labelpreparar3.setText(ingPreparacion[2]);
                labelpreparar4.setText(ingPreparacion[3]);
                break;
            case 5:
                labelpreparar1.setText(ingPreparacion[0]);
                labelpreparar2.setText(ingPreparacion[1]);
                labelpreparar3.setText(ingPreparacion[2]);
                labelpreparar4.setText(ingPreparacion[3]);
                labelpreparar5.setText(ingPreparacion[4]);
                break;
            default:
                labelpreparar1.setText("");
                labelpreparar2.setText("");
                labelpreparar3.setText("");
                labelpreparar4.setText("");
                labelpreparar5.setText("");
                break;
        }

    }//actualizar preparación

    /*-----------------------NO TOCAR------------------*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TimerLbl = new javax.swing.JLabel();
        ingrediente5Label = new javax.swing.JLabel();
        LabelBasurero = new javax.swing.JLabel();
        labelPlato = new javax.swing.JLabel();
        ingrediente2Label = new javax.swing.JLabel();
        ingrediente3Label = new javax.swing.JLabel();
        ingrediente4Label = new javax.swing.JLabel();
        ingrediente1Label = new javax.swing.JLabel();
        labelpreparar4 = new javax.swing.JLabel();
        labelpreparar3 = new javax.swing.JLabel();
        labelpreparar5 = new javax.swing.JLabel();
        labelpreparar2 = new javax.swing.JLabel();
        labelpreparar1 = new javax.swing.JLabel();
        ButtonEntregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 450));
        jPanel1.setLayout(null);

        TimerLbl.setBackground(new java.awt.Color(255, 255, 255));
        TimerLbl.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        TimerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimerLbl.setText("Timer");
        TimerLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(TimerLbl);
        TimerLbl.setBounds(710, 10, 80, 40);

        ingrediente5Label.setForeground(new java.awt.Color(255, 255, 255));
        ingrediente5Label.setText("jLabel2");
        ingrediente5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingrediente5LabelMouseClicked(evt);
            }
        });
        jPanel1.add(ingrediente5Label);
        ingrediente5Label.setBounds(730, 250, 37, 16);

        LabelBasurero.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        LabelBasurero.setForeground(new java.awt.Color(204, 0, 0));
        LabelBasurero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBasurero.setText("           Basurero");
        LabelBasurero.setToolTipText("");
        LabelBasurero.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LabelBasurero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBasureroMouseClicked(evt);
            }
        });
        jPanel1.add(LabelBasurero);
        LabelBasurero.setBounds(600, 350, 200, 90);

        labelPlato.setBackground(new java.awt.Color(255, 255, 255));
        labelPlato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPlato.setForeground(new java.awt.Color(255, 255, 153));
        labelPlato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPlatoMouseClicked(evt);
            }
        });
        jPanel1.add(labelPlato);
        labelPlato.setBounds(220, 240, 80, 20);

        ingrediente2Label.setForeground(new java.awt.Color(255, 255, 255));
        ingrediente2Label.setText("jLabel2");
        ingrediente2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingrediente2LabelMouseClicked(evt);
            }
        });
        jPanel1.add(ingrediente2Label);
        ingrediente2Label.setBounds(580, 250, 37, 16);

        ingrediente3Label.setForeground(new java.awt.Color(255, 255, 255));
        ingrediente3Label.setText("jLabel2");
        ingrediente3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingrediente3LabelMouseClicked(evt);
            }
        });
        jPanel1.add(ingrediente3Label);
        ingrediente3Label.setBounds(630, 250, 37, 16);

        ingrediente4Label.setForeground(new java.awt.Color(255, 255, 255));
        ingrediente4Label.setText("jLabel2");
        ingrediente4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingrediente4LabelMouseClicked(evt);
            }
        });
        jPanel1.add(ingrediente4Label);
        ingrediente4Label.setBounds(680, 250, 37, 16);

        ingrediente1Label.setForeground(new java.awt.Color(255, 255, 255));
        ingrediente1Label.setText("jLabel2");
        ingrediente1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingrediente1LabelMouseClicked(evt);
            }
        });
        jPanel1.add(ingrediente1Label);
        ingrediente1Label.setBounds(530, 250, 37, 16);

        labelpreparar4.setBackground(new java.awt.Color(255, 255, 255));
        labelpreparar4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelpreparar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labelpreparar4);
        labelpreparar4.setBounds(240, 132, 50, 20);

        labelpreparar3.setBackground(new java.awt.Color(255, 255, 255));
        labelpreparar3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelpreparar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labelpreparar3);
        labelpreparar3.setBounds(240, 162, 50, 20);

        labelpreparar5.setBackground(new java.awt.Color(255, 255, 51));
        labelpreparar5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelpreparar5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labelpreparar5);
        labelpreparar5.setBounds(240, 102, 50, 20);

        labelpreparar2.setBackground(new java.awt.Color(255, 255, 255));
        labelpreparar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelpreparar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labelpreparar2);
        labelpreparar2.setBounds(240, 192, 50, 20);

        labelpreparar1.setBackground(new java.awt.Color(255, 255, 255));
        labelpreparar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelpreparar1.setForeground(new java.awt.Color(255, 255, 153));
        labelpreparar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labelpreparar1);
        labelpreparar1.setBounds(240, 232, 50, 20);

        ButtonEntregar.setBackground(new java.awt.Color(153, 0, 51));
        ButtonEntregar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        ButtonEntregar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEntregar.setText("Entregar");
        ButtonEntregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));
        ButtonEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEntregarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonEntregar);
        ButtonEntregar.setBounds(190, 280, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/GameBackground.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelBasureroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBasureroMouseClicked
        // TODO add your handling code here:
        if (ingAux.getTipo() != null) {
            lis.botar(ingAux);
            lis.mueveIzq();
            lis.contarIngredientesNoVacios();
            actualizaringredientes();
            ingAux = new Ingredientes();
        }

    }//GEN-LAST:event_LabelBasureroMouseClicked

    private void ingrediente1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrediente1LabelMouseClicked
        // TODO add your handling code here:
        ingAux.setId(Integer.parseInt(tiposIngredientes[0][0]));
        ingAux.setTipo(tiposIngredientes[0][1]);
        JOptionPane.showMessageDialog(null, ingAux);
    }//GEN-LAST:event_ingrediente1LabelMouseClicked

    private void ingrediente2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrediente2LabelMouseClicked
        // TODO add your handling code here:
        ingAux.setId(Integer.parseInt(tiposIngredientes[1][0]));
        ingAux.setTipo(tiposIngredientes[1][1]);
        JOptionPane.showMessageDialog(null, ingAux);
    }//GEN-LAST:event_ingrediente2LabelMouseClicked

    private void ingrediente3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrediente3LabelMouseClicked
        // TODO add your handling code here:
        ingAux.setId(Integer.parseInt(tiposIngredientes[2][0]));
        ingAux.setTipo(tiposIngredientes[2][1]);
        JOptionPane.showMessageDialog(null, ingAux);
    }//GEN-LAST:event_ingrediente3LabelMouseClicked

    private void ingrediente4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrediente4LabelMouseClicked
        // TODO add your handling code here:
        ingAux.setId(Integer.parseInt(tiposIngredientes[3][0]));
        ingAux.setTipo(tiposIngredientes[3][1]);
        JOptionPane.showMessageDialog(null, ingAux);
    }//GEN-LAST:event_ingrediente4LabelMouseClicked

    private void ingrediente5LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrediente5LabelMouseClicked
        // TODO add your handling code here:
        ingAux.setId(Integer.parseInt(tiposIngredientes[4][0]));
        ingAux.setTipo(tiposIngredientes[4][1]);
        JOptionPane.showMessageDialog(null, ingAux);
    }//GEN-LAST:event_ingrediente5LabelMouseClicked

    private void labelPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPlatoMouseClicked
        // TODO add your handling code here:
        //Aqui se va a elaborar el pedido
        if (ingAux.getTipo() != null && ingAux.getTipo() != "vacio") {
            lis.botar(ingAux);
            lis.mueveIzq();
            lis.contarIngredientesNoVacios();
            actualizaringredientes();

            if (pilaPreparar.tamanio() < 5) {
                pilaPreparar.push(ingAux);
            }

            ingAux = new Ingredientes();
            actualizarpreparacion();

        }
    }//GEN-LAST:event_labelPlatoMouseClicked

    private void ButtonEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEntregarActionPerformed
        // TODO add your handling code here:

        if (!pilaPreparar.Vacia()) {
            pilaPreparar = new Pila();
            actualizarpreparacion();
        }
    }//GEN-LAST:event_ButtonEntregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEntregar;
    private javax.swing.JLabel LabelBasurero;
    private javax.swing.JLabel TimerLbl;
    private javax.swing.JLabel ingrediente1Label;
    private javax.swing.JLabel ingrediente2Label;
    private javax.swing.JLabel ingrediente3Label;
    private javax.swing.JLabel ingrediente4Label;
    private javax.swing.JLabel ingrediente5Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPlato;
    private javax.swing.JLabel labelpreparar1;
    private javax.swing.JLabel labelpreparar2;
    private javax.swing.JLabel labelpreparar3;
    private javax.swing.JLabel labelpreparar4;
    private javax.swing.JLabel labelpreparar5;
    // End of variables declaration//GEN-END:variables
}
